language: python

python:
  - 3.7

install:
  - pip install -r mysite/requirements.txt

before_script:
  - python mysite/manage.py makemigrations 
  - python mysite/manage.py migrate
  - python mysite/manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run mysite/manage.py test


after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  github_token: $GITHUB_TOKEN
  region: us-east-1
  app: ebdjango
  env: django-env
  bucket_name: awscache-ebdjango-bucket
  on:
      repo: aya0221/swe1-app
      branch: main
