language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

before_script:
  # - python manage.py makemigrations 
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  # - coverage run --source=ebdjango,polls manage.py test
  - coverage run --source=polls manage.py test
  - coverage report -m


after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  github-token: $GITHUB_TOKEN
  region: us-east-1
  app: ebdjango
  env: django-env
  bucket_name: awscache-ebdjango-bucket
  on:
      repo: aya0221/swe1-app
      branch: main
